on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: 'Hola World'
      uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: ${{ secrets.SUPER_SECRET }}
